[pytest]
python_files = test_*.py
python_functions = test_*
markers =
    positive: Позитивные тесты (проверяют, что код работает как надо)
    negative: Негативные тесты (проверяют граничные случаи)
    